### ISSUE TITLE
WARNING: Undefined substitution referenced: "nbsp".

### ISSUE THREAD

**Issue by GlenNicholls** [sphinx-toolbox/sphinx-toolbox#80]
## Description

I have enabled the regex extension like so:

```
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.viewcode',
    'sphinx_toolbox.more_autodoc.regex',
]
```

However, I get the following warning:

```
/.../schema.py:docstring of pyeda...SOME_RE:1: WARNING: Undefined substitution referenced: "nbsp".
```

For

```
SOME_RE: object = re.compile("^\\w+:[a-zA-Z]+$")
"""Some Regex."""
```

This feels like user error to me, but I don't see anything obvious in [the docs](https://sphinx-toolbox.readthedocs.io/en/latest/extensions/more_autodoc/regex.html?highlight=regex) to fix this. Is there something else I'm supposed to do to get that warning to go away? The pattern looks fine, but the type just shows

```
Type: |nbsp| |nbsp| |nbsp| |nbsp| object
```

## Version

  * Operating System: Centos 7 and Ubuntu 20.04
  * Python: 3.8
  * sphinx-toolbox: 2.15.1

## Installation source

Installed via pip

**Comment by domdfcoding** [comment]
Sorry for the wait. I have released version [2.15.3](https://pypi.org/project/sphinx-toolbox/2.15.3/) which should fix this issue. Can you try with that version?

**Comment by GlenNicholls** [comment]
No worries! Okay, I just pulled that down and I'm still seeing the same issue. I also tested it with and without a type hint and it still shows the `|npsp|`'s that don't link anywhere.

Is there something else I can try?

**Comment by domdfcoding** [comment]
Ah, I've found another issue where the substitution is missing if the `rst_prolog` option is used. Have you set a value for that in your conf.py file? If you have can you try installing the current master branch and see if that fixes your issue?

**Comment by GlenNicholls** [comment]
Alright, it looks like that fixed it. Out of curiosity, this is what it's supposed to look like? Also, what is the |nbsp| substitution anyways?

![image](https://user-images.githubusercontent.com/17171913/149406775-8e7d811d-345b-4f3b-80d0-c0c543a5376e.png)

**Comment by domdfcoding** [comment]
That looks right. The `|nbsp|` substitution sticks in a little space so it isn't all cramped up. 

![image](https://user-images.githubusercontent.com/8050853/149793293-fef20ae0-b4b9-4882-99c1-b75103baec9c.png)


I will make a release now. Sorry for any trouble.

**Comment by GlenNicholls** [comment]
Awesome, the latest release has this issue fixed. It was no trouble at all, thank you for taking the time to look into it!
